;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	counsel-M-x
	counsel-find-file
	indent-for-tab-command
	indent-pp-sexp
	overwrite-mode
	))

(setq mc/cmds-to-run-once
      '(
	avy-goto-char
	dabbrev-completion
	eval-last-sexp
	evil-next-visual-line
	hungry-delete-backward
	hungry-delete-forward
	iedit-switch-to-mc-mode
	ivy-switch-buffer
	mouse-set-region
	org-self-insert-command
	))
